import { Header, Footer, Visual, SectionHeading, ProgrammeCard, CTA, therapies } from "@/components/site";

const concerns=["Speech Delay","Behavioural Challenges","Learning Difficulties","Social Skills","Sensory Processing","Attention & Focus"];
const benefits=["Experienced Professionals","Personalised Care","Evidence-Based Approach","Parent Partnership"];
const why=["Experienced Professionals","Personalised Care","Safe & Nurturing Environment","Focus on Real Life Progress"];

export default function Home(){return <><Header/><main>
<section className="hero"><div className="container hero-grid"><div><span className="eyebrow">Child Development Centre</span><h1 className="serif">Every Child Has a <em>Brighter Tomorrow</em></h1><p className="hero-copy">Compassionate, evidence-based support for your child’s unique journey.</p><div className="actions"><a className="btn" href="/consultation">Book a Consultation →</a><a className="btn alt" href="/about">Learn More</a></div></div><div className="hero-visual"><Visual label="A child exploring with a toy plane"/></div></div><div className="container hero-benefits">{benefits.map((x,i)=><div className="benefit" key={x}><i>{['♡','●','▥','♥'][i]}</i>{x}</div>)}</div></section>
<section className="section"><div className="container"><SectionHeading eyebrow="Our Programmes" title="Support for every stage of your child’s journey." copy="Structured programmes that meet children where they are and help families move forward with clarity." center/><div className="cards-4">{[...require("@/components/site").programmes].map((p:any)=><ProgrammeCard key={p.title} p={p}/>)}</div></div></section>
<section className="section"><div className="container split-banner"><Visual label="Parent and child"/><div className="split-copy"><span className="eyebrow">You’re not alone</span><h2 className="serif">We’re Here to Help</h2><p>Raising a child with developmental differences can feel challenging. At Devine CDC, we walk this journey with you — with expertise, empathy and personalised care.</p><a className="btn" href="/team">Talk to Our Team →</a></div></div></section>
<section className="section"><div className="container"><SectionHeading eyebrow="Common Concerns" title="Start with what you’re noticing." copy="Support for a wide range of developmental needs." center/><div className="concerns">{concerns.map((x,i)=><a className="concern" href="/therapies" key={x}><i>{['⌁','♧','▣','♣','✦','◉'][i]}</i>{x}</a>)}</div></div></section>
<section className="section"><div className="container"><SectionHeading eyebrow="Our Therapies" title="Evidence-based, compassionate and personalised." center/><div className="therapy-grid">{therapies.map((x,i)=><a className="therapy-tile" href="/therapies" key={x[0]}><i>{['◌','◉','↗','▣','♡','◒'][i]}</i><h3>{x[0]}</h3></a>)}</div></div></section>
<section className="section approach"><div className="container"><SectionHeading eyebrow="Our Approach" title="A holistic, child-centred and family-focused approach." center/><div className="steps">{[['1','Understand','Detailed discussion to know your child'],['2','Plan','Personalised goals and strategy'],['3','Therapy','One-on-one and group sessions'],['4','Progress','Track, review and celebrate milestones']].map(s=><div className="step" key={s[0]}><div className="step-number">{s[0]}</div><h3>{s[1]}</h3><p>{s[2]}</p></div>)}</div></div></section>
<section className="section"><div className="container"><SectionHeading eyebrow="Why Families Choose Devine" title="Care that feels thoughtful, clear and human." center/><div className="why-grid">{why.map((x,i)=><div className="why" key={x}><i>{['♡','★','⌂','♧'][i]}</i><h3>{x}</h3></div>)}</div></div></section>
<section className="section"><div className="container"><SectionHeading eyebrow="Small Wins, Big Journeys" title="Every step forward matters." copy="Real progress can be quiet — and still be meaningful." center/><div className="quote-box"><p>“My child is more confident and communicates so much better now. We’re so grateful to the Devine team!”</p><small>— Parent</small></div></div></section>
<CTA/>
</main><Footer/></>}
